version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    # otherwise auto-merge without merge-queue might break checksums
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
