---
kind: pipeline
name: nixos-tests
type: exec

steps:
- name: test
  commands:
  - nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz -A sops-install-secrets.tests
  - nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-21.05.tar.gz -A sops-install-secrets.tests
---
kind: signature
hmac: df547336a0317ffe1dd419138c0552b79189c7caf0cc86c98bba9ca5bea22ea9

...
