---
kind: pipeline
name: nixos-tests

steps:
- name: test
  image: busybox
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    SSL_CERT_FILE: /nix/var/nix/profiles/system/etc/ssl/certs/ca-bundle.crt
    PAGER: cat
    USER: root
  volumes:
    - name: socket
      path: /nix/var/nix/daemon-socket/socket
  volumes:
    - name: nixstore
      path: /nix
  commands:
  - nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz -A sops-install-secrets.tests
  - nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-20.03.tar.gz -A sops-install-secrets.tests
volumes:
- name: nixstore
  host:
    path: /nix
---
kind: signature
hmac: 1d9dc0576a5f871c84ac9fd1919fcbd85a7e68fe927f8467d1bfc856fa0c5967

...
