linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - dogsled
    - err113
    - exhaustruct
    - exportloopref
    - forbidigo
    - funlen
    - gocognit
    - gocyclo
    - godot
    - godox
    - lll
    - maintidx
    - mnd
    - nestif
    - varnamelen
